# Netflix Data Analysis

## 1. Data Loading

In [2]:
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving netflix_titles.csv to netflix_titles.csv

## 2. Initial Data Exploration

In [4]:
df_raw=pd.read_csv('netflix_titles.csv')
df_raw.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
df_raw.shape

(8807, 12)

In [7]:
df_raw.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
df_raw.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

## 3. Handling Missing Values

In [9]:
df=df_raw.copy()

In [10]:
#Clean
df['director']=df['director'].fillna('Unknown')
df['cast']=df['cast'].fillna('Unknown')
df['country']=df['country'].fillna('Unknown')
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [11]:
#drop
df=df.dropna(subset=['date_added','rating','duration'])

In [12]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

## 4. Content Type Analysis

In [13]:
df['type'].value_counts()

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [14]:
df.groupby('release_year')['type'].value_counts().head(80)

release_year  type
1925          TV Show     1
1942          Movie       2
1943          Movie       3
1944          Movie       3
1945          Movie       3
                         ..
2000          Movie      33
              TV Show     4
2001          Movie      40
              TV Show     5
2002          Movie      44
Name: count, Length: 80, dtype: int64

## 5. Feature Engineering: Decade

In [15]:

df['decade']=(df['release_year']//10)*10

In [16]:
df['decade']

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
8802    2000
8803    2010
8804    2000
8805    2000
8806    2010
Name: decade, Length: 8790, dtype: int64

In [17]:
df.groupby('decade')['type'].value_counts()

decade  type
1920    TV Show       1
1940    Movie        13
        TV Show       2
1950    Movie        11
1960    Movie        23
        TV Show       2
1970    Movie        66
        TV Show       4
1980    Movie       122
        TV Show       7
1990    Movie       241
        TV Show      33
2000    Movie       677
        TV Show     130
2010    Movie      4179
        TV Show    1734
2020    Movie       794
        TV Show     751
Name: count, dtype: int64

## 6. Country Analysis

In [18]:
df['country'].value_counts().head()

country
United States     2809
India              972
Unknown            829
United Kingdom     418
Japan              243
Name: count, dtype: int64

In [19]:
countries=['United States','India','Unknown','United Kingdom','Japan']
df_top=df[df['country'].isin(countries)]
df_top.groupby('country')['type'].value_counts()

country         type
India           Movie       893
                TV Show      79
Japan           TV Show     167
                Movie        76
United Kingdom  TV Show     212
                Movie       206
United States   Movie      2055
                TV Show     754
Unknown         Movie       439
                TV Show     390
Name: count, dtype: int64

In [20]:
df[df['type']=='Movie'].value_counts()

show_id  type   title                    director                        cast                                                                                                                                                                         country                 date_added          release_year  rating  duration  listed_in                                         description                                                                                                                                               decade
s999     Movie  Searching For Sheela     Unknown                         Ma Anand Sheela                                                                                                                                                              India                   April 22, 2021      2021          TV-14   58 min    Documentaries, International Movies               Journalists and fans await Ma Anand Sheela as the infamous former Rajneesh commune’s spokesperson returns to India after decades for an interview tour.   2020      1
s1       Movie  Dick Johnson Is Dead     Kirsten Johnson                 Unknown                                                                                                                                                                      United States           September 25, 2021  2020          PG-13   90 min    Documentaries                                     As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.  2020      1
s10      Movie  The Starling             Theodore Melfi                  Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor       United States           September 24, 2021  2021          PG-13   104 min   Comedies, Dramas                                  A woman adjusting to life after a loss contends with a feisty bird that's taken over her garden — and a husband who's struggling to find a way forward.   2020      1
s1000    Movie  Stowaway                 Joe Penna                       Anna Kendrick, Toni Collette, Daniel Dae Kim, Shamier Anderson                                                                                                               Germany, United States  April 22, 2021      2021          TV-MA   116 min   Dramas, International Movies, Thrillers           A three-person crew on a mission to Mars faces an impossible choice when an unplanned passenger jeopardizes the lives of everyone on board.               2020      1
s1001    Movie  Wild Dog                 Ahishor Solomon                 Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, Atul Kulakarni, Bilal Hussain, Ali Reza, Mayank Parakh                                                                          Unknown                 April 22, 2021      2020          TV-MA   126 min   Action & Adventure, International Movies          A brash but brilliant Indian intelligence agent leads a covert operation to nab the mastermind behind a series of attacks threatening national security.  2020      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
s1019    Movie  Jaane Tu... Ya Jaane Na  Abbas Tyrewala                  Imran Khan, Genelia D'Souza, Manjari Fadnis, Ayaz Khan, Prateik Babbar, Ratna Pathak Shah, Arbaaz Khan, Sohail Khan                                                          India                   April 17, 2021      2008          TV-14   147 min   Comedies, International Movies, Music & Musicals  Soft-spoken Jai and spitfire beauty Aditi couldn't be more different – but their family and friends know that they're a perfect match.                    2000      1
s102     Movie  Untold: Breaking Point   Chapman Way, Maclain Way        Unknown                                                                                                                                                                      United States           September 7, 2021   2021          TV-MA   80 min    Documentaries, Sports Movies                      Under pressure to continue a winning tradition in American tennis, Mardy Fish faced mental health challenges that changed his life on and off the court.  2020      1
s1020    Movie  Lagaan                   Ashutosh Gowariker              Aamir Khan, Gracy Singh, Rachel Shelley, Paul Blackthorne, Kulbhushan Kharbanda, Raghuvir Yadav, Yashpal Sharma, Rajendranath Zutshi, Rajesh Vivek, Aditya Lakhia            India, United Kingdom   April 17, 2021      2001          PG      224 min   Dramas, International Movies, Music & Musicals    In 1890s India, an arrogant British commander challenges the harshly taxed residents of Champaner to a high-stakes cricket match.                         2000      1
s1021    Movie  Madness in the Desert    Satyajit Bhatkal                Aamir Khan, Ashutosh Gowariker                                                                                                                                               India                   April 17, 2021      2004          TV-14   141 min   Documentaries, International Movies               The story of making "Lagaan," one of the millennium's seminal Indian films, is told from the point of view of production team member Satyajit Bhatkal.    2000      1
s1022    Movie  Peepli Live              Anusha Rizvi, Mahmood Farooqui  Omkar Das Manikpuri, Raghuvir Yadav, Malaika Shenoy, Nawazuddin Siddiqui, Naseeruddin Shah, Sitaram Panchal, Shalini Vatsa, Farrukh Jaffar, Aamir Bashir, Vishal Om Prakash  India                   April 17, 2021      2010          TV-MA   109 min   Comedies, Dramas, Independent Movies              Two indigent farmers consider suicide so that their families can collect a government subsidy that's paid to the relatives of deceased farmers.           2010      1
Name: count, Length: 6126, dtype: int64

In [21]:
df['country'].nunique()

749

In [22]:
df_india=df[df['country']=='India']
df_india.groupby('country')['type'].value_counts()

country  type
India    Movie      893
         TV Show     79
Name: count, dtype: int64

In [23]:
df['decade'].value_counts().head(1)

decade
2010    5913
Name: count, dtype: int64

In [24]:
three_countries=['United States','India','Unknown']
Top_Three_Countries=df[df['country'].isin(three_countries)]
Top_Three_Countries.groupby('country')['type'].value_counts()

country        type
India          Movie       893
               TV Show      79
United States  Movie      2055
               TV Show     754
Unknown        Movie       439
               TV Show     390
Name: count, dtype: int64

In [25]:
Unknown=(len(df[df['country']=='Unknown'])/len(df.index))*100
print(f"Percentage of Unknown countries:{Unknown}")

Percentage of Unknown countries:9.431171786120592

## 7. Genre Analysis

In [26]:
df['listed_in']=df['listed_in'].str.split(", ")

In [27]:
df=df.explode('listed_in')
df['listed_in'].value_counts().head()

listed_in
International Movies      2752
Dramas                    2426
Comedies                  1674
International TV Shows    1349
Documentaries              869
Name: count, dtype: int64

## 8. Cast Analysis

In [28]:
df['cast']=df['cast'].str.split(", ")
df=df.explode('cast')
df['cast'].value_counts().head(10)

cast
Unknown             1504
Anupam Kher          120
Shah Rukh Khan        99
Naseeruddin Shah      92
Akshay Kumar          85
Paresh Rawal          79
Om Puri               78
Amitabh Bachchan      76
Takahiro Sakurai      75
Yuki Kaji             73
Name: count, dtype: int64